language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - REPO_NAME=cakephp-vat-number-check
    - PLUGIN_NAME=VatNumberCheck
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2

  matrix:
    - DB=mysql CAKE_VERSION=2.6
    - DB=mysql CAKE_VERSION=2.7
    - DB=mysql CAKE_VERSION=2.8
    - DB=mysql CAKE_VERSION=2.9

matrix:
  include:
    - php: 5.6
      env:
        - COVERALLS=1
    - php: 5.6
      env:
        - PHPCS=1
    - php: 5.6
      env:
        - FOC_VALIDATE=1
  exclude:
    - php: 7
      env: DB=mysql CAKE_VERSION=2.6
    - php: 7
      env: DB=mysql CAKE_VERSION=2.7
    - php: 7
      env: DB=mysql CAKE_VERSION=2.8

branches:
  only:
    - master

before_script:
  - git clone -b master https://github.com/Oefenweb/travis --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
  hipchat:
    rooms:
      secure: B46Xvke4nkoN+ivLs0Ubn64rAKOQplqDwLoE9KZDJ6O0XxiAZIZoNXcrGovP+qAB8LHRbGZvOUG4u+YZt9I41bgBAuCM2wZTFJe85IzLjROLxlSXwKDH4tey31omYTSYFKm7Tg9Gi2a6hyGN/YDytiUlmJqUvElcN0EUfkXzxS4=
