language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - REPO_NAME=cakephp-vat-number-check
    - PLUGIN_NAME=VatNumberCheck
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2

    - secure: "fzh9d+tjlq3CUyUdO3XMA0JcHbRyOiwXTGlSFYuDvP9tWV+fQFj7nfCm1K8Kp4P+wEwhXIfNpsAd75h/xjg83m/MhxyzHWxRWWz9F68HA74oQj+NkBskYS9j7fq4KUQyR6l+o06IQSW0OAd/A9W2dXTOATvgGcxwsxpGqpvPHqk="

  matrix:
    - CAKE_VERSION=2.9
    - CAKE_VERSION=2.10 PHPUNIT_VERSION=^5.7

matrix:
  include:
    - php: 7.1
      env:
        - CODECOVERAGE=1 PHPUNIT_VERSION=^5.7
    - php: 7.1
      env:
        - PHPCS=1
    - php: 7.1
      env:
        - FOC_VALIDATE=1
  exclude:
    - php: 7.2
      env: CAKE_VERSION=2.9

branches:
  only:
    - master

before_script:
  - git clone -b master https://github.com/Oefenweb/travis --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
  hipchat:
    rooms:
      secure: B46Xvke4nkoN+ivLs0Ubn64rAKOQplqDwLoE9KZDJ6O0XxiAZIZoNXcrGovP+qAB8LHRbGZvOUG4u+YZt9I41bgBAuCM2wZTFJe85IzLjROLxlSXwKDH4tey31omYTSYFKm7Tg9Gi2a6hyGN/YDytiUlmJqUvElcN0EUfkXzxS4=
